/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BookingRooms service. Represents a row in the &quot;wrm_BookingRooms&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.BookingRoomsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.BookingRoomsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingRooms
 * @see com.cignexdatamatics.wrm.model.impl.BookingRoomsImpl
 * @see com.cignexdatamatics.wrm.model.impl.BookingRoomsModelImpl
 * @generated
 */
public interface BookingRoomsModel extends BaseModel<BookingRooms> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a booking rooms model instance should use the {@link BookingRooms} interface instead.
	 */

	/**
	 * Returns the primary key of this booking rooms.
	 *
	 * @return the primary key of this booking rooms
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this booking rooms.
	 *
	 * @param primaryKey the primary key of this booking rooms
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the b r mapping ID of this booking rooms.
	 *
	 * @return the b r mapping ID of this booking rooms
	 */
	public long getBRMappingId();

	/**
	 * Sets the b r mapping ID of this booking rooms.
	 *
	 * @param BRMappingId the b r mapping ID of this booking rooms
	 */
	public void setBRMappingId(long BRMappingId);

	/**
	 * Returns the booking ID of this booking rooms.
	 *
	 * @return the booking ID of this booking rooms
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this booking rooms.
	 *
	 * @param bookingId the booking ID of this booking rooms
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the room ID of this booking rooms.
	 *
	 * @return the room ID of this booking rooms
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this booking rooms.
	 *
	 * @param roomId the room ID of this booking rooms
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the booking date of this booking rooms.
	 *
	 * @return the booking date of this booking rooms
	 */
	public Date getBookingDate();

	/**
	 * Sets the booking date of this booking rooms.
	 *
	 * @param bookingDate the booking date of this booking rooms
	 */
	public void setBookingDate(Date bookingDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BookingRooms bookingRooms);

	public int hashCode();

	public CacheModel<BookingRooms> toCacheModel();

	public BookingRooms toEscapedModel();

	public String toString();

	public String toXmlString();
}