/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CityMaster service. Represents a row in the &quot;wrm_CityMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.CityMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.CityMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CityMaster
 * @see com.cignexdatamatics.wrm.model.impl.CityMasterImpl
 * @see com.cignexdatamatics.wrm.model.impl.CityMasterModelImpl
 * @generated
 */
public interface CityMasterModel extends BaseModel<CityMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city master model instance should use the {@link CityMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this city master.
	 *
	 * @return the primary key of this city master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city master.
	 *
	 * @param primaryKey the primary key of this city master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the city ID of this city master.
	 *
	 * @return the city ID of this city master
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this city master.
	 *
	 * @param cityId the city ID of this city master
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the city name of this city master.
	 *
	 * @return the city name of this city master
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this city master.
	 *
	 * @param cityName the city name of this city master
	 */
	public void setCityName(String cityName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CityMaster cityMaster);

	public int hashCode();

	public CacheModel<CityMaster> toCacheModel();

	public CityMaster toEscapedModel();

	public String toString();

	public String toXmlString();
}