/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FacilityMaster service. Represents a row in the &quot;wrm_FacilityMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.FacilityMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.FacilityMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacilityMaster
 * @see com.cignexdatamatics.wrm.model.impl.FacilityMasterImpl
 * @see com.cignexdatamatics.wrm.model.impl.FacilityMasterModelImpl
 * @generated
 */
public interface FacilityMasterModel extends BaseModel<FacilityMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility master model instance should use the {@link FacilityMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this facility master.
	 *
	 * @return the primary key of this facility master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility master.
	 *
	 * @param primaryKey the primary key of this facility master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the facilities ID of this facility master.
	 *
	 * @return the facilities ID of this facility master
	 */
	public long getFacilitiesId();

	/**
	 * Sets the facilities ID of this facility master.
	 *
	 * @param facilitiesId the facilities ID of this facility master
	 */
	public void setFacilitiesId(long facilitiesId);

	/**
	 * Returns the facilities name of this facility master.
	 *
	 * @return the facilities name of this facility master
	 */
	@AutoEscape
	public String getFacilitiesName();

	/**
	 * Sets the facilities name of this facility master.
	 *
	 * @param facilitiesName the facilities name of this facility master
	 */
	public void setFacilitiesName(String facilitiesName);

	/**
	 * Returns the facilities desc of this facility master.
	 *
	 * @return the facilities desc of this facility master
	 */
	@AutoEscape
	public String getFacilitiesDesc();

	/**
	 * Sets the facilities desc of this facility master.
	 *
	 * @param facilitiesDesc the facilities desc of this facility master
	 */
	public void setFacilitiesDesc(String facilitiesDesc);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FacilityMaster facilityMaster);

	public int hashCode();

	public CacheModel<FacilityMaster> toCacheModel();

	public FacilityMaster toEscapedModel();

	public String toString();

	public String toXmlString();
}