/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FloorMaster service. Represents a row in the &quot;wrm_FloorMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.FloorMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.FloorMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FloorMaster
 * @see com.cignexdatamatics.wrm.model.impl.FloorMasterImpl
 * @see com.cignexdatamatics.wrm.model.impl.FloorMasterModelImpl
 * @generated
 */
public interface FloorMasterModel extends BaseModel<FloorMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a floor master model instance should use the {@link FloorMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this floor master.
	 *
	 * @return the primary key of this floor master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this floor master.
	 *
	 * @param primaryKey the primary key of this floor master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the floor ID of this floor master.
	 *
	 * @return the floor ID of this floor master
	 */
	public long getFloorId();

	/**
	 * Sets the floor ID of this floor master.
	 *
	 * @param floorId the floor ID of this floor master
	 */
	public void setFloorId(long floorId);

	/**
	 * Returns the location ID of this floor master.
	 *
	 * @return the location ID of this floor master
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this floor master.
	 *
	 * @param locationId the location ID of this floor master
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the floor name of this floor master.
	 *
	 * @return the floor name of this floor master
	 */
	@AutoEscape
	public String getFloorName();

	/**
	 * Sets the floor name of this floor master.
	 *
	 * @param floorName the floor name of this floor master
	 */
	public void setFloorName(String floorName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FloorMaster floorMaster);

	public int hashCode();

	public CacheModel<FloorMaster> toCacheModel();

	public FloorMaster toEscapedModel();

	public String toString();

	public String toXmlString();
}