/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NewBooking service. Represents a row in the &quot;wrm_NewBooking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.NewBookingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.NewBookingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewBooking
 * @see com.cignexdatamatics.wrm.model.impl.NewBookingImpl
 * @see com.cignexdatamatics.wrm.model.impl.NewBookingModelImpl
 * @generated
 */
public interface NewBookingModel extends BaseModel<NewBooking> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a new booking model instance should use the {@link NewBooking} interface instead.
	 */

	/**
	 * Returns the primary key of this new booking.
	 *
	 * @return the primary key of this new booking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this new booking.
	 *
	 * @param primaryKey the primary key of this new booking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the booking ID of this new booking.
	 *
	 * @return the booking ID of this new booking
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this new booking.
	 *
	 * @param bookingId the booking ID of this new booking
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the meeting title of this new booking.
	 *
	 * @return the meeting title of this new booking
	 */
	@AutoEscape
	public String getMeetingTitle();

	/**
	 * Sets the meeting title of this new booking.
	 *
	 * @param meetingTitle the meeting title of this new booking
	 */
	public void setMeetingTitle(String meetingTitle);

	/**
	 * Returns the meeting desc of this new booking.
	 *
	 * @return the meeting desc of this new booking
	 */
	@AutoEscape
	public String getMeetingDesc();

	/**
	 * Sets the meeting desc of this new booking.
	 *
	 * @param meetingDesc the meeting desc of this new booking
	 */
	public void setMeetingDesc(String meetingDesc);

	/**
	 * Returns the host ID of this new booking.
	 *
	 * @return the host ID of this new booking
	 */
	public long getHostId();

	/**
	 * Sets the host ID of this new booking.
	 *
	 * @param hostId the host ID of this new booking
	 */
	public void setHostId(long hostId);

	/**
	 * Returns the from date of this new booking.
	 *
	 * @return the from date of this new booking
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this new booking.
	 *
	 * @param fromDate the from date of this new booking
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this new booking.
	 *
	 * @return the to date of this new booking
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this new booking.
	 *
	 * @param toDate the to date of this new booking
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the start time of this new booking.
	 *
	 * @return the start time of this new booking
	 */
	@AutoEscape
	public String getStartTime();

	/**
	 * Sets the start time of this new booking.
	 *
	 * @param startTime the start time of this new booking
	 */
	public void setStartTime(String startTime);

	/**
	 * Returns the end time of this new booking.
	 *
	 * @return the end time of this new booking
	 */
	@AutoEscape
	public String getEndTime();

	/**
	 * Sets the end time of this new booking.
	 *
	 * @param endTime the end time of this new booking
	 */
	public void setEndTime(String endTime);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(NewBooking newBooking);

	public int hashCode();

	public CacheModel<NewBooking> toCacheModel();

	public NewBooking toEscapedModel();

	public String toString();

	public String toXmlString();
}