/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RoomMaster service. Represents a row in the &quot;wrm_RoomMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cignexdatamatics.wrm.model.impl.RoomMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cignexdatamatics.wrm.model.impl.RoomMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoomMaster
 * @see com.cignexdatamatics.wrm.model.impl.RoomMasterImpl
 * @see com.cignexdatamatics.wrm.model.impl.RoomMasterModelImpl
 * @generated
 */
public interface RoomMasterModel extends BaseModel<RoomMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a room master model instance should use the {@link RoomMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this room master.
	 *
	 * @return the primary key of this room master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this room master.
	 *
	 * @param primaryKey the primary key of this room master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room ID of this room master.
	 *
	 * @return the room ID of this room master
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this room master.
	 *
	 * @param roomId the room ID of this room master
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the city ID of this room master.
	 *
	 * @return the city ID of this room master
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this room master.
	 *
	 * @param cityId the city ID of this room master
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the location ID of this room master.
	 *
	 * @return the location ID of this room master
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this room master.
	 *
	 * @param locationId the location ID of this room master
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the floor ID of this room master.
	 *
	 * @return the floor ID of this room master
	 */
	public long getFloorId();

	/**
	 * Sets the floor ID of this room master.
	 *
	 * @param floorId the floor ID of this room master
	 */
	public void setFloorId(long floorId);

	/**
	 * Returns the room name of this room master.
	 *
	 * @return the room name of this room master
	 */
	@AutoEscape
	public String getRoomName();

	/**
	 * Sets the room name of this room master.
	 *
	 * @param roomName the room name of this room master
	 */
	public void setRoomName(String roomName);

	/**
	 * Returns the capacity of this room master.
	 *
	 * @return the capacity of this room master
	 */
	public long getCapacity();

	/**
	 * Sets the capacity of this room master.
	 *
	 * @param capacity the capacity of this room master
	 */
	public void setCapacity(long capacity);

	/**
	 * Returns the extension of this room master.
	 *
	 * @return the extension of this room master
	 */
	public long getExtension();

	/**
	 * Sets the extension of this room master.
	 *
	 * @param extension the extension of this room master
	 */
	public void setExtension(long extension);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(RoomMaster roomMaster);

	public int hashCode();

	public CacheModel<RoomMaster> toCacheModel();

	public RoomMaster toEscapedModel();

	public String toString();

	public String toXmlString();
}