/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model.impl;

import com.cignexdatamatics.wrm.model.BookingAttendees;
import com.cignexdatamatics.wrm.model.BookingAttendeesModel;
import com.cignexdatamatics.wrm.service.persistence.BookingAttendeesPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BookingAttendees service. Represents a row in the &quot;wrm_BookingAttendees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cignexdatamatics.wrm.model.BookingAttendeesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookingAttendeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingAttendeesImpl
 * @see com.cignexdatamatics.wrm.model.BookingAttendees
 * @see com.cignexdatamatics.wrm.model.BookingAttendeesModel
 * @generated
 */
public class BookingAttendeesModelImpl extends BaseModelImpl<BookingAttendees>
	implements BookingAttendeesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booking attendees model instance should use the {@link com.cignexdatamatics.wrm.model.BookingAttendees} interface instead.
	 */
	public static final String TABLE_NAME = "wrm_BookingAttendees";
	public static final Object[][] TABLE_COLUMNS = {
			{ "attendeesId", Types.BIGINT },
			{ "bookingId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table wrm_BookingAttendees (attendeesId LONG not null,bookingId LONG not null,primary key (attendeesId, bookingId))";
	public static final String TABLE_SQL_DROP = "drop table wrm_BookingAttendees";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cignexdatamatics.wrm.model.BookingAttendees"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cignexdatamatics.wrm.model.BookingAttendees"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cignexdatamatics.wrm.model.BookingAttendees"),
			true);
	public static long ATTENDEESID_COLUMN_BITMASK = 1L;
	public static long BOOKINGID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cignexdatamatics.wrm.model.BookingAttendees"));

	public BookingAttendeesModelImpl() {
	}

	public BookingAttendeesPK getPrimaryKey() {
		return new BookingAttendeesPK(_attendeesId, _bookingId);
	}

	public void setPrimaryKey(BookingAttendeesPK primaryKey) {
		setAttendeesId(primaryKey.attendeesId);
		setBookingId(primaryKey.bookingId);
	}

	public Serializable getPrimaryKeyObj() {
		return new BookingAttendeesPK(_attendeesId, _bookingId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((BookingAttendeesPK)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return BookingAttendees.class;
	}

	public String getModelClassName() {
		return BookingAttendees.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("attendeesId", getAttendeesId());
		attributes.put("bookingId", getBookingId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long attendeesId = (Long)attributes.get("attendeesId");

		if (attendeesId != null) {
			setAttendeesId(attendeesId);
		}

		Long bookingId = (Long)attributes.get("bookingId");

		if (bookingId != null) {
			setBookingId(bookingId);
		}
	}

	public long getAttendeesId() {
		return _attendeesId;
	}

	public void setAttendeesId(long attendeesId) {
		_columnBitmask |= ATTENDEESID_COLUMN_BITMASK;

		if (!_setOriginalAttendeesId) {
			_setOriginalAttendeesId = true;

			_originalAttendeesId = _attendeesId;
		}

		_attendeesId = attendeesId;
	}

	public long getOriginalAttendeesId() {
		return _originalAttendeesId;
	}

	public long getBookingId() {
		return _bookingId;
	}

	public void setBookingId(long bookingId) {
		_columnBitmask |= BOOKINGID_COLUMN_BITMASK;

		if (!_setOriginalBookingId) {
			_setOriginalBookingId = true;

			_originalBookingId = _bookingId;
		}

		_bookingId = bookingId;
	}

	public long getOriginalBookingId() {
		return _originalBookingId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public BookingAttendees toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (BookingAttendees)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		BookingAttendeesImpl bookingAttendeesImpl = new BookingAttendeesImpl();

		bookingAttendeesImpl.setAttendeesId(getAttendeesId());
		bookingAttendeesImpl.setBookingId(getBookingId());

		bookingAttendeesImpl.resetOriginalValues();

		return bookingAttendeesImpl;
	}

	public int compareTo(BookingAttendees bookingAttendees) {
		BookingAttendeesPK primaryKey = bookingAttendees.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		BookingAttendees bookingAttendees = null;

		try {
			bookingAttendees = (BookingAttendees)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		BookingAttendeesPK primaryKey = bookingAttendees.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		BookingAttendeesModelImpl bookingAttendeesModelImpl = this;

		bookingAttendeesModelImpl._originalAttendeesId = bookingAttendeesModelImpl._attendeesId;

		bookingAttendeesModelImpl._setOriginalAttendeesId = false;

		bookingAttendeesModelImpl._originalBookingId = bookingAttendeesModelImpl._bookingId;

		bookingAttendeesModelImpl._setOriginalBookingId = false;

		bookingAttendeesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BookingAttendees> toCacheModel() {
		BookingAttendeesCacheModel bookingAttendeesCacheModel = new BookingAttendeesCacheModel();

		bookingAttendeesCacheModel.attendeesId = getAttendeesId();

		bookingAttendeesCacheModel.bookingId = getBookingId();

		return bookingAttendeesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{attendeesId=");
		sb.append(getAttendeesId());
		sb.append(", bookingId=");
		sb.append(getBookingId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.cignexdatamatics.wrm.model.BookingAttendees");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>attendeesId</column-name><column-value><![CDATA[");
		sb.append(getAttendeesId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bookingId</column-name><column-value><![CDATA[");
		sb.append(getBookingId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BookingAttendees.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			BookingAttendees.class
		};
	private long _attendeesId;
	private long _originalAttendeesId;
	private boolean _setOriginalAttendeesId;
	private long _bookingId;
	private long _originalBookingId;
	private boolean _setOriginalBookingId;
	private long _columnBitmask;
	private BookingAttendees _escapedModelProxy;
}