/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model.impl;

import com.cignexdatamatics.wrm.model.BookingFacilityMapping;
import com.cignexdatamatics.wrm.model.BookingFacilityMappingModel;
import com.cignexdatamatics.wrm.service.persistence.BookingFacilityMappingPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BookingFacilityMapping service. Represents a row in the &quot;wrm_BookingFacilityMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cignexdatamatics.wrm.model.BookingFacilityMappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookingFacilityMappingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingFacilityMappingImpl
 * @see com.cignexdatamatics.wrm.model.BookingFacilityMapping
 * @see com.cignexdatamatics.wrm.model.BookingFacilityMappingModel
 * @generated
 */
public class BookingFacilityMappingModelImpl extends BaseModelImpl<BookingFacilityMapping>
	implements BookingFacilityMappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booking facility mapping model instance should use the {@link com.cignexdatamatics.wrm.model.BookingFacilityMapping} interface instead.
	 */
	public static final String TABLE_NAME = "wrm_BookingFacilityMapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bookingId", Types.BIGINT },
			{ "facilitiesId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table wrm_BookingFacilityMapping (bookingId LONG not null,facilitiesId LONG not null,primary key (bookingId, facilitiesId))";
	public static final String TABLE_SQL_DROP = "drop table wrm_BookingFacilityMapping";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cignexdatamatics.wrm.model.BookingFacilityMapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cignexdatamatics.wrm.model.BookingFacilityMapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cignexdatamatics.wrm.model.BookingFacilityMapping"),
			true);
	public static long BOOKINGID_COLUMN_BITMASK = 1L;
	public static long FACILITIESID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cignexdatamatics.wrm.model.BookingFacilityMapping"));

	public BookingFacilityMappingModelImpl() {
	}

	public BookingFacilityMappingPK getPrimaryKey() {
		return new BookingFacilityMappingPK(_bookingId, _facilitiesId);
	}

	public void setPrimaryKey(BookingFacilityMappingPK primaryKey) {
		setBookingId(primaryKey.bookingId);
		setFacilitiesId(primaryKey.facilitiesId);
	}

	public Serializable getPrimaryKeyObj() {
		return new BookingFacilityMappingPK(_bookingId, _facilitiesId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((BookingFacilityMappingPK)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return BookingFacilityMapping.class;
	}

	public String getModelClassName() {
		return BookingFacilityMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bookingId", getBookingId());
		attributes.put("facilitiesId", getFacilitiesId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long bookingId = (Long)attributes.get("bookingId");

		if (bookingId != null) {
			setBookingId(bookingId);
		}

		Long facilitiesId = (Long)attributes.get("facilitiesId");

		if (facilitiesId != null) {
			setFacilitiesId(facilitiesId);
		}
	}

	public long getBookingId() {
		return _bookingId;
	}

	public void setBookingId(long bookingId) {
		_columnBitmask |= BOOKINGID_COLUMN_BITMASK;

		if (!_setOriginalBookingId) {
			_setOriginalBookingId = true;

			_originalBookingId = _bookingId;
		}

		_bookingId = bookingId;
	}

	public long getOriginalBookingId() {
		return _originalBookingId;
	}

	public long getFacilitiesId() {
		return _facilitiesId;
	}

	public void setFacilitiesId(long facilitiesId) {
		_columnBitmask |= FACILITIESID_COLUMN_BITMASK;

		if (!_setOriginalFacilitiesId) {
			_setOriginalFacilitiesId = true;

			_originalFacilitiesId = _facilitiesId;
		}

		_facilitiesId = facilitiesId;
	}

	public long getOriginalFacilitiesId() {
		return _originalFacilitiesId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public BookingFacilityMapping toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (BookingFacilityMapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		BookingFacilityMappingImpl bookingFacilityMappingImpl = new BookingFacilityMappingImpl();

		bookingFacilityMappingImpl.setBookingId(getBookingId());
		bookingFacilityMappingImpl.setFacilitiesId(getFacilitiesId());

		bookingFacilityMappingImpl.resetOriginalValues();

		return bookingFacilityMappingImpl;
	}

	public int compareTo(BookingFacilityMapping bookingFacilityMapping) {
		BookingFacilityMappingPK primaryKey = bookingFacilityMapping.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		BookingFacilityMapping bookingFacilityMapping = null;

		try {
			bookingFacilityMapping = (BookingFacilityMapping)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		BookingFacilityMappingPK primaryKey = bookingFacilityMapping.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		BookingFacilityMappingModelImpl bookingFacilityMappingModelImpl = this;

		bookingFacilityMappingModelImpl._originalBookingId = bookingFacilityMappingModelImpl._bookingId;

		bookingFacilityMappingModelImpl._setOriginalBookingId = false;

		bookingFacilityMappingModelImpl._originalFacilitiesId = bookingFacilityMappingModelImpl._facilitiesId;

		bookingFacilityMappingModelImpl._setOriginalFacilitiesId = false;

		bookingFacilityMappingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BookingFacilityMapping> toCacheModel() {
		BookingFacilityMappingCacheModel bookingFacilityMappingCacheModel = new BookingFacilityMappingCacheModel();

		bookingFacilityMappingCacheModel.bookingId = getBookingId();

		bookingFacilityMappingCacheModel.facilitiesId = getFacilitiesId();

		return bookingFacilityMappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{bookingId=");
		sb.append(getBookingId());
		sb.append(", facilitiesId=");
		sb.append(getFacilitiesId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.cignexdatamatics.wrm.model.BookingFacilityMapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bookingId</column-name><column-value><![CDATA[");
		sb.append(getBookingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilitiesId</column-name><column-value><![CDATA[");
		sb.append(getFacilitiesId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BookingFacilityMapping.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			BookingFacilityMapping.class
		};
	private long _bookingId;
	private long _originalBookingId;
	private boolean _setOriginalBookingId;
	private long _facilitiesId;
	private long _originalFacilitiesId;
	private boolean _setOriginalFacilitiesId;
	private long _columnBitmask;
	private BookingFacilityMapping _escapedModelProxy;
}