/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model.impl;

import com.cignexdatamatics.wrm.model.CityMaster;
import com.cignexdatamatics.wrm.model.CityMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CityMaster service. Represents a row in the &quot;wrm_CityMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cignexdatamatics.wrm.model.CityMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CityMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CityMasterImpl
 * @see com.cignexdatamatics.wrm.model.CityMaster
 * @see com.cignexdatamatics.wrm.model.CityMasterModel
 * @generated
 */
public class CityMasterModelImpl extends BaseModelImpl<CityMaster>
	implements CityMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a city master model instance should use the {@link com.cignexdatamatics.wrm.model.CityMaster} interface instead.
	 */
	public static final String TABLE_NAME = "wrm_CityMaster";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cityId", Types.BIGINT },
			{ "cityName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table wrm_CityMaster (cityId LONG not null primary key,cityName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table wrm_CityMaster";
	public static final String ORDER_BY_JPQL = " ORDER BY cityMaster.cityName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY wrm_CityMaster.cityName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cignexdatamatics.wrm.model.CityMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cignexdatamatics.wrm.model.CityMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cignexdatamatics.wrm.model.CityMaster"),
			true);
	public static long CITYNAME_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cignexdatamatics.wrm.model.CityMaster"));

	public CityMasterModelImpl() {
	}

	public long getPrimaryKey() {
		return _cityId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCityId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_cityId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CityMaster.class;
	}

	public String getModelClassName() {
		return CityMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cityId", getCityId());
		attributes.put("cityName", getCityName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cityId = (Long)attributes.get("cityId");

		if (cityId != null) {
			setCityId(cityId);
		}

		String cityName = (String)attributes.get("cityName");

		if (cityName != null) {
			setCityName(cityName);
		}
	}

	public long getCityId() {
		return _cityId;
	}

	public void setCityId(long cityId) {
		_cityId = cityId;
	}

	public String getCityName() {
		if (_cityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityName;
		}
	}

	public void setCityName(String cityName) {
		_columnBitmask = -1L;

		if (_originalCityName == null) {
			_originalCityName = _cityName;
		}

		_cityName = cityName;
	}

	public String getOriginalCityName() {
		return GetterUtil.getString(_originalCityName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CityMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CityMaster toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CityMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CityMasterImpl cityMasterImpl = new CityMasterImpl();

		cityMasterImpl.setCityId(getCityId());
		cityMasterImpl.setCityName(getCityName());

		cityMasterImpl.resetOriginalValues();

		return cityMasterImpl;
	}

	public int compareTo(CityMaster cityMaster) {
		int value = 0;

		value = getCityName().compareTo(cityMaster.getCityName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CityMaster cityMaster = null;

		try {
			cityMaster = (CityMaster)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = cityMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CityMasterModelImpl cityMasterModelImpl = this;

		cityMasterModelImpl._originalCityName = cityMasterModelImpl._cityName;

		cityMasterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CityMaster> toCacheModel() {
		CityMasterCacheModel cityMasterCacheModel = new CityMasterCacheModel();

		cityMasterCacheModel.cityId = getCityId();

		cityMasterCacheModel.cityName = getCityName();

		String cityName = cityMasterCacheModel.cityName;

		if ((cityName != null) && (cityName.length() == 0)) {
			cityMasterCacheModel.cityName = null;
		}

		return cityMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{cityId=");
		sb.append(getCityId());
		sb.append(", cityName=");
		sb.append(getCityName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.cignexdatamatics.wrm.model.CityMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cityId</column-name><column-value><![CDATA[");
		sb.append(getCityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityName</column-name><column-value><![CDATA[");
		sb.append(getCityName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CityMaster.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CityMaster.class
		};
	private long _cityId;
	private String _cityName;
	private String _originalCityName;
	private long _columnBitmask;
	private CityMaster _escapedModelProxy;
}