/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cignexdatamatics.wrm.model.impl;

import com.cignexdatamatics.wrm.model.LocationMaster;
import com.cignexdatamatics.wrm.model.LocationMasterModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LocationMaster service. Represents a row in the &quot;wrm_LocationMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cignexdatamatics.wrm.model.LocationMasterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LocationMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LocationMasterImpl
 * @see com.cignexdatamatics.wrm.model.LocationMaster
 * @see com.cignexdatamatics.wrm.model.LocationMasterModel
 * @generated
 */
public class LocationMasterModelImpl extends BaseModelImpl<LocationMaster>
	implements LocationMasterModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a location master model instance should use the {@link com.cignexdatamatics.wrm.model.LocationMaster} interface instead.
	 */
	public static final String TABLE_NAME = "wrm_LocationMaster";
	public static final Object[][] TABLE_COLUMNS = {
			{ "locationId", Types.BIGINT },
			{ "cityId", Types.BIGINT },
			{ "locationName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table wrm_LocationMaster (locationId LONG not null primary key,cityId LONG,locationName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table wrm_LocationMaster";
	public static final String ORDER_BY_JPQL = " ORDER BY locationMaster.cityId ASC, locationMaster.locationName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY wrm_LocationMaster.cityId ASC, wrm_LocationMaster.locationName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cignexdatamatics.wrm.model.LocationMaster"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cignexdatamatics.wrm.model.LocationMaster"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cignexdatamatics.wrm.model.LocationMaster"),
			true);
	public static long CITYID_COLUMN_BITMASK = 1L;
	public static long LOCATIONNAME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cignexdatamatics.wrm.model.LocationMaster"));

	public LocationMasterModelImpl() {
	}

	public long getPrimaryKey() {
		return _locationId;
	}

	public void setPrimaryKey(long primaryKey) {
		setLocationId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_locationId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return LocationMaster.class;
	}

	public String getModelClassName() {
		return LocationMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("locationId", getLocationId());
		attributes.put("cityId", getCityId());
		attributes.put("locationName", getLocationName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long locationId = (Long)attributes.get("locationId");

		if (locationId != null) {
			setLocationId(locationId);
		}

		Long cityId = (Long)attributes.get("cityId");

		if (cityId != null) {
			setCityId(cityId);
		}

		String locationName = (String)attributes.get("locationName");

		if (locationName != null) {
			setLocationName(locationName);
		}
	}

	public long getLocationId() {
		return _locationId;
	}

	public void setLocationId(long locationId) {
		_locationId = locationId;
	}

	public long getCityId() {
		return _cityId;
	}

	public void setCityId(long cityId) {
		_columnBitmask = -1L;

		if (!_setOriginalCityId) {
			_setOriginalCityId = true;

			_originalCityId = _cityId;
		}

		_cityId = cityId;
	}

	public long getOriginalCityId() {
		return _originalCityId;
	}

	public String getLocationName() {
		if (_locationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _locationName;
		}
	}

	public void setLocationName(String locationName) {
		_columnBitmask = -1L;

		if (_originalLocationName == null) {
			_originalLocationName = _locationName;
		}

		_locationName = locationName;
	}

	public String getOriginalLocationName() {
		return GetterUtil.getString(_originalLocationName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LocationMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LocationMaster toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (LocationMaster)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		LocationMasterImpl locationMasterImpl = new LocationMasterImpl();

		locationMasterImpl.setLocationId(getLocationId());
		locationMasterImpl.setCityId(getCityId());
		locationMasterImpl.setLocationName(getLocationName());

		locationMasterImpl.resetOriginalValues();

		return locationMasterImpl;
	}

	public int compareTo(LocationMaster locationMaster) {
		int value = 0;

		if (getCityId() < locationMaster.getCityId()) {
			value = -1;
		}
		else if (getCityId() > locationMaster.getCityId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getLocationName().toLowerCase()
					.compareTo(locationMaster.getLocationName().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		LocationMaster locationMaster = null;

		try {
			locationMaster = (LocationMaster)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = locationMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LocationMasterModelImpl locationMasterModelImpl = this;

		locationMasterModelImpl._originalCityId = locationMasterModelImpl._cityId;

		locationMasterModelImpl._setOriginalCityId = false;

		locationMasterModelImpl._originalLocationName = locationMasterModelImpl._locationName;

		locationMasterModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LocationMaster> toCacheModel() {
		LocationMasterCacheModel locationMasterCacheModel = new LocationMasterCacheModel();

		locationMasterCacheModel.locationId = getLocationId();

		locationMasterCacheModel.cityId = getCityId();

		locationMasterCacheModel.locationName = getLocationName();

		String locationName = locationMasterCacheModel.locationName;

		if ((locationName != null) && (locationName.length() == 0)) {
			locationMasterCacheModel.locationName = null;
		}

		return locationMasterCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{locationId=");
		sb.append(getLocationId());
		sb.append(", cityId=");
		sb.append(getCityId());
		sb.append(", locationName=");
		sb.append(getLocationName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.cignexdatamatics.wrm.model.LocationMaster");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>locationId</column-name><column-value><![CDATA[");
		sb.append(getLocationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityId</column-name><column-value><![CDATA[");
		sb.append(getCityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationName</column-name><column-value><![CDATA[");
		sb.append(getLocationName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LocationMaster.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			LocationMaster.class
		};
	private long _locationId;
	private long _cityId;
	private long _originalCityId;
	private boolean _setOriginalCityId;
	private String _locationName;
	private String _originalLocationName;
	private long _columnBitmask;
	private LocationMaster _escapedModelProxy;
}